platform: cpp

shared:
    settings:
        env.MVN_MAKE_OPTS: --batch-mode

    notifications:
        email: "zookeeper-devel@oath.com"

    steps:
        dist_force_push:
            description: Push packages to dist
            command: gmake dist_force_push
        git_tag:
            description: Git tag after successful release
            command: gmake git_tag
    plugins:
        coverage:
            enabled: false
        test_results:
            type: junit
            parameters:
                path: "test_results"

jobs:
  component:
    steps:
      publish:
        dist-branch: "test"
    #publish step only publishes c-client packages; dist_force_push publishes zookeeper_core package to rhel6 and rhel7
    order: [environment, install-rpms, init, build, package, dist_force_push, publish, git_tag]
  pull-request:
    order: [environment, install-rpms, init, build, package]
