platform: cpp

shared:
    settings:
        env.MVN_MAKE_OPTS: --batch-mode

    notifications:
        email: "zookeeper-devel@yahoo-inc.com"

    steps:
        git_tag:
            description: Git tag after successful release
            command: gmake git_tag
    plugins:
        coverage:
            enabled: false
        test_results:
            type: junit
            parameters:
                path: "test_results"

jobs:
  component:
    order: [environment, install-rpms, init, build, package, publish, git_tag]
  pull-request:
    order: [environment, install-rpms, init, build, package]
