jobs:
  pull-request:
    requires: [~pr]
    steps:
      - print_env: set
      - build: gmake ${SD_SETTING_MAKE_ARGS} platforms
      - package: gmake ${SD_SETTING_MAKE_ARGS} package-release

  merge:
    requires: [~commit]
    steps:
      - print_env: set
      - build: gmake ${SD_SETTING_MAKE_ARGS} platforms
      - package: gmake ${SD_SETTING_MAKE_ARGS} package-release
      - dist_force_push: gmake dist_force_push
      - git_tag: gmake git_tag

shared:
  image: docker-registry.ops.yahoo.com:4443/storm/storm-ci-docker-image-rhel-7.5.4:latest
  annotations:
    screwdriver.cd/cpu: HIGH
    screwdriver.cd/ram: HIGH
  environment:
    USER_SHELL_BIN: bash
    SD_ZIP_ARTIFACTS: false
  settings:
    email:
      addresses: [ zookeeper-devel@verizonmedia.com ]
      statuses: [ FAILURE ]
