platform: cpp

shared:
    settings:
        env.MVN_MAKE_OPTS: --batch-mode

    notifications:
        email: "zookeeper-devel@yahoo-inc.com"

    plugins:
        coverage:
            enabled: false
        test_results:
            enabled: false

jobs:
  component:
    order: [environment, install-rpms, init, build, package, publish]
  pull-request:
    order: [environment, install-rpms, init, build, package]
